spring.application.name=msvc-cia


spring.ai.openai.api-key=${OPENAI_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.5
spring.ai.openai.chat.options.parallel-tool-calls=true
spring.ai.vectorstore.pgvector.index-type=hnsw

aws.accessKeyId=${ACCESS_KEY}
aws.secretKey=${SECRET_KEY}
aws.bucketName=${BUCKET_NAME}
aws.bucketUrl=${BUCKET_URL}


spring.ai.vectorstore.pgvector.initialize-schema=true
spring.ai.vectorstore.pgvector.distance-type=cosine_distance
spring.ai.vectors
spring.datasource.url=jdbc:postgresql://192.168.1.5:5433/ciadb
spring.datasource.username=${PG_USER}
spring.datasource.password=${PG_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver





